import QueryBuilder from '@components/QueryBuilder'
import { Table } from '@components/Table'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <QueryBuilder query={[]} onChangeQuery={function (query: Query[]): void {
        throw new Error('Function not implemented.')
      } }/>

      <Table documents={[{tags:[],_id:1232, title: "Hello", createdAt: new Date(), createdBy:"Raul Ignacio", folio:"3diqddi", expediente: "ihdicq0ec", area:"Nulidad"},{tags:[],_id:3222, title: "HI", createdAt: new Date(), createdBy:"Raul Ignacio", folio:"3gagagdi", expediente: "ihsx0ebc", area:"Legal"}]}/>
       
    </div>
  )
}

export default Home
