import { Button, NonIdealState } from '@blueprintjs/core'
import Head from 'next/head'
import type { NextPage } from 'next'
import QueryBuilder from '@components/QueryBuilder'
import React from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [ queries, setQueries ] = React.useState<Query[]>([
    {
      header: "header",
      operator: "contains",
      value: "value",
    },
    {
      header: "header",
      operator: "eq",
      value: "value",
    },
    {
      header: "header",
      operator: "contains",
      value: "value",
    },
    {
      header: "header",
      operator: "contains",
      value: "value",
    }
  ]);
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <QueryBuilder queries={queries} onChangeQuery={setQueries} maxQueries={5}/>
      <NonIdealState
                    icon="search"
                    iconSize={16}
                    title={"No results"}
                    description={"Try a new query to get started."}
                    action={<Button icon="plus" text="New search" />}
                    layout={"horizontal"}
                />
    </div>
  )
}

export default Home
